### ISSUE TITLE
Often getting the error "Request limit exceeded." using AWS API. Is aws.max_retries the solution?

### ISSUE THREAD

**Issue by keymon** [cloudfoundry-incubator/bosh-aws-cpi-release#19]
When deploying a CF installation on AWS, sometimes I hit the error `AWS::EC2::Errors::RequestLimitExceeded Request limit exceeded.`. 

In some portions of the code of this CPI, [some calls are wrapped around a decorator which retries the requests](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/eb9f26d419a5c94f5996fb82285fb29fc5515b89/src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb#L166), but there are several calls to the API that are not wrapped but that call the AWS api via the AWS sdk library used, specially when querying the existing state (e.g. listing AMI images).

In [this PR the solution is wrap](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/pull/17#issuecomment-158827233) all the AWS client with some retry logic in the CPI code, but as said, there are several inexplicit calls to the API  that are not wrapped.

But I do think that [the configuration `max_entries`](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/118ea6df1fd6c9f9c2116a5e47a27cfb33e834c9/src/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L37) can solve that. bosh-aws-cpi uses the AWS sdk v1 (latest version is v2), and [reviewing the SDK code](https://github.com/aws/aws-sdk-ruby/blob/aws-sdk-v1/lib/aws/core/client.rb) it seems the requests are retried by the library. 

So, if using a higher value of `aws.max_entries` this issue can be solved, I suggest either increase the default value and/or document the issue and the setting, as the issue is really common. I also wonder if we need to wrap the code with `Bosh::Common.retryable` at all.

Error example:

``` 
D, [2016-01-12 09:53:13 #18310] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:matt
D, [2016-01-12 09:53:13 #18310] [create_missing_vm(runner_z1, 0/1)] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":{"type":"Unknown","message":"Request limit exceeded.","ok_to_retry":false},"log":"Rescued Unknown: Request limit exceeded.. backtrace: /var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:375:in `return_or_raise'\n/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:476:in `client_request'\n(eval):3:in `describe_images'\n/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/ec2/resource.rb:72:in `describe_call'\n/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/ec2/resource.rb:56:in `get_resource'\n/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/resource.rb:235:in `block (2 levels) in define_attribute_getter'\n/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/cacheable.rb:63:in `retrieve_attribute'\n/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/ec2/resource.rb:66:in `retrieve_attribute'\n/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/resource.rb:235:in `block in define_attribute_getter'\n/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb:120:in `build_instance_params'\n/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb:81:in `create'\n/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/cloud.rb:127:in `block in create_vm'\n/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_common-1.3071.0/lib/common/thread_formatter.rb:49:in `with_thread_name'\n/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/cloud.rb:122:in `create_vm'\n/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3071.0/lib/bosh/cpi/cli.rb:71:in `public_send'\n/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3071.0/lib/bosh/cpi/cli.rb:71:in `run'\n/var/vcap/packages/bosh_aws_cpi/bin/aws_cpi:28:in `<main>'"}, err: I, [2016-01-12T09:53:10.833273 #18490]  INFO -- : [AWS EC2 200 0.134925 0 retries] describe_regions()  

I, [2016-01-12T09:53:11.073708 #18490]  INFO -- : [AWS EC2 200 0.229609 0 retries] describe_images(:filters=>[{:name=>"image-id",:values=>["ami-8bf7c4fc"]}])  

I, [2016-01-12T09:53:13.168565 #18490]  INFO -- : [AWS EC2 503 2.078879 2 retries] describe_images(:image_ids=>["ami-8bf7c4fc"]) AWS::EC2::Errors::RequestLimitExceeded Request limit exceeded.

E, [2016-01-12T09:53:13.169478 #18490] ERROR -- : Failed to create instance: Request limit exceeded.
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:375:in `return_or_raise'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `describe_images'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/ec2/resource.rb:72:in `describe_call'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/ec2/resource.rb:56:in `get_resource'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/resource.rb:235:in `block (2 levels) in define_attribute_getter'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/cacheable.rb:63:in `retrieve_attribute'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/ec2/resource.rb:66:in `retrieve_attribute'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/resource.rb:235:in `block in define_attribute_getter'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb:120:in `build_instance_params'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb:81:in `create'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/cloud.rb:127:in `block in create_vm'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_common-1.3071.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/cloud.rb:122:in `create_vm'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3071.0/lib/bosh/cpi/cli.rb:71:in `public_send'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3071.0/lib/bosh/cpi/cli.rb:71:in `run'
/var/vcap/packages/bosh_aws_cpi/bin/aws_cpi:28:in `<main>'
, exit_status: pid 18483 exit 0
E, [2016-01-12 09:53:13 #18310] [create_missing_vm(runner_z1, 0/1)] ERROR -- DirectorJobRunner: error creating vm: Unknown CPI error 'Unknown' with message 'Request limit exceeded.'

I, [2016-01-12T09:53:13.333183 #18476]  INFO -- : [AWS EC2 503 2.252245 2 retries] describe_images(:filters=>[{:name=>"image-id",:values=>["ami-8bf7c4fc"]}]) AWS::EC2::Errors::RequestLimitExceeded Request limit exceeded.

, exit_status: pid 18463 exit 0
I, [2016-01-12 09:53:13 #18310] [create_missing_vm(runner_z1, 0/1)]  INFO -- DirectorJobRunner: Cleaning up the created VM due to an error: Unknown CPI error 'Unknown' with message 'Request limit exceeded.'
D, [2016-01-12 09:53:13 #18310] [] DEBUG -- DirectorJobRunner: Worker thread raised exception: Unknown CPI error 'Unknown' with message 'Request limit exceeded.' - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3153.0/lib/cloud/external_cpi.rb:108:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3153.0/lib/cloud/external_cpi.rb:89:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3153.0/lib/cloud/external_cpi.rb:51:in `create_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/vm_creator.rb:41:in `create'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/resource_pool_updater.rb:51:in `create_missing_vm'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/resource_pool_updater.rb:34:in `block (4 levels) in create_missing_vms'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3153.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/resource_pool_updater.rb:32:in `block (3 levels) in create_missing_vms'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/event_log.rb:50:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/resource_pool_updater.rb:31:in `block (2 levels) in create_missing_vms'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3153.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3153.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3153.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3153.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
``` 

Following some stacktraces, I identified these points where this error can raise:

https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb#L121
``` 
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:375:in `return_or_raise'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `describe_images'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/ec2/resource.rb:72:in `describe_call'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/ec2/resource.rb:56:in `get_resource'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/resource.rb:235:in `block (2 levels) in define_attribute_getter'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/cacheable.rb:63:in `retrieve_attribute'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/ec2/resource.rb:66:in `retrieve_attribute'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/resource.rb:235:in `block in define_attribute_getter'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb:120:in `build_instance_params'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb:81:in `create'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/cloud.rb:127:in `block in create_vm'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_common-1.3071.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/cloud.rb:122:in `create_vm'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3071.0/lib/bosh/cpi/cli.rb:71:in `public_send'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3071.0/lib/bosh/cpi/cli.rb:71:in `run'
/var/vcap/packages/bosh_aws_cpi/bin/aws_cpi:28:in `<main>'
``` 

https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/src/bosh_aws_cpi/lib/cloud/aws/stemcell.rb#L9
``` 
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:375:in `return_or_raise'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `describe_images'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/aws-sdk-v1-1.60.2/lib/aws/ec2/image.rb:220:in `exists?'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/stemcell.rb:9:in `find'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/stemcell_finder.rb:8:in `find_by_region_and_id'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/cloud.rb:124:in `block in create_vm'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_common-1.3071.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_aws_cpi/lib/cloud/aws/cloud.rb:122:in `create_vm'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3071.0/lib/bosh/cpi/cli.rb:71:in `public_send'
/var/vcap/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3071.0/lib/bosh/cpi/cli.rb:71:in `run'
/var/vcap/packages/bosh_aws_cpi/bin/aws_cpi:28:in `<main>'
```

**Comment by cppforlife** [comment]
@keymon Did you have a chance to bump max_retries in your env? Did that eliminate number of errors for your deployment size?

**Comment by keymon** [comment]
@cppforlife to be sincere I had no time to do a test. I might get some time later today or tomorrow. 

My idea was test it by creating 32x vms in parallel with a custom manifest and increasing the threads in bosh. That will likely trigger the rate limiting consistently.

**Comment by keymon** [comment]
I am trying to test this now, but bad luck, now I am not able to trigger the Rate limit from AWS :(

Anyway, just comment that although the CPI code [does accept this configuration from the file `cpi.json`](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/118ea6df1fd6c9f9c2116a5e47a27cfb33e834c9/src/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L37), the [template that renders `cpi.json` and the `spec`](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/118ea6df1fd6c9f9c2116a5e47a27cfb33e834c9/jobs/aws_cpi/templates/cpi.json.erb#L7) do not include it. It is not documented either.

**Comment by keymon** [comment]
I was finally able to reproduce the Rate limit issue using a bigger box (`m4.xlarge`, the CPU was throttling me :smile: ), 64 threads and deploying 64 vms in parallel.

Note that I **manually** changed the file `/var/vcap/jobs/aws_cpi/config/cpi.json` in my bosh director, to include the config `cloud.plugin.aws.properties.aws.max_retries` as follows:

``` 
{"cloud":{"plugin":"aws","properties":{"aws":{"max_retries": 16, "credentials_source":"env_or_profile",
```

I tested it by setting it with values 0, 2 and 16. 

With 0 I immediately get the Request Limit error. With 2 (the default) happens less often, but happens. Setting `max_retries: 16`  it manages to create all the VMs and I can see with `bosh task X --debug` that the CPI is retrying:

```
I, [2016-01-14T19:01:44.094289 #11148]  INFO -- : [AWS EC2 200 16.495747 5 retries] describe_instances(:instance_ids=>["i-82f1180a"])  
I, [2016-01-14T19:02:22.088647 #11148]  INFO -- : [AWS EC2 200 35.992445 6 retries] describe_instances(:instance_ids=>["i-82f1180a"])  
I, [2016-01-14T19:02:23.600540 #11033]  INFO -- : [AWS EC2 200 63.866485 7 retries] describe_instances(:instance_ids=>["i-2eff16a6"])  
I, [2016-01-14T19:01:27.567377 #10805]  INFO -- : [AWS EC2 200 8.762974 4 retries] run_instances(:block_device_mappings=>[{:device_name=>"/dev/sdb",:ebs=>{:delete_on_termination=>true,:volume_size=>10,:volume_type=>"gp2"}}],:client_token=>"...",:image_id=>"ami-8bf7c4fc",:instance_type=>"m3.medium",:key_name=>"hector_key_pair",:max_count=>1,:min_count=>1,:placement=>{:availability_zone=>"eu-west-1a"},:private_ip_address=>"10.0.10.56",:security_group_ids=>["sg-5b63193f"],:subnet_id=>"subnet-64d5c101",:user_data=>"...")  
I, [2016-01-14T19:01:44.195799 #10805]  INFO -- : [AWS EC2 200 16.627039 5 retries] describe_instances(:instance_ids=>["i-8df31a05"])  
I, [2016-01-14T19:02:24.349135 #10805]  INFO -- : [AWS EC2 200 33.960596 6 retries] describe_instances(:instance_ids=>["i-8df31a05"])  
I, [2016-01-14T19:02:29.452754 #10803]  INFO -- : [AWS EC2 200 68.826496 7 retries] describe_instances(:instance_ids=>["i-12f1189a"])  
I, [2016-01-14T19:02:30.176219 #10803]  INFO -- : [AWS EC2 200 0.721453 1 retries] describe_addresses(:filters=>[{:name=>"instance-id",:values=>["i-12f1189a"]}])  

```

We can do more testing, but seems worth it to invest some time.

Summarising:

 * The configuration `aws.max_retries` is consumed by `aws-sdk-ruby` to retry failed calls to the AWS API which are secure to retry, like the rate limiting ones.
 * Increase this value will solve the errors related to Rate limiting.

I suggest that the next steps are:
 * AWS CPI already configures such option if set in `cpi.json`
 * But it is not implemented in the release job template and spec.
 * The option requires some documentation.
 * We should revisit if the retry logic for the case of Rate limit errors at the CPI level is required at all.

**Comment by cppforlife** [comment]
@keymon thanks for details notes. we'll expose max_retries configuration and document it.

**Comment by cppforlife** [comment]
https://www.pivotaltracker.com/story/show/112949377

**Comment by keymon** [comment]
@cppforlife thank you.

There is a PR waiting exposing this variable, and it would be really easy to review: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/pull/23

**Comment by cppforlife** [comment]
Exposed `max_retries` in v44.

**Comment by keymon** [comment]
After a pair of weeks of usage, with `max_retries=8`, we confirm that the most of the errors disappeared and the situation improved a lot. 

We still experience some issues, but when we are running several deployments in parallel with 32 threads in each deployment.

I suggest we close this issue.
