### ISSUE TITLE
bosh create-env failing on Amazon Linux AMI

### ISSUE THREAD

**Issue by mkjelland** [cloudfoundry-incubator/bosh-aws-cpi-release#58]
Hello, we are trying to install a bosh director on AWS and getting an error when running bosh create-env from an Amazon Linux AMI instance. It did work from an EC2 Ubuntu instance.

This is the error we are seeing:
```
creating stemcell (bosh-aws-xen-hvm-ubuntu-trusty-go_agent 3421.4):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"undefined method `set_api' for #\u003cClass:0x0055c51465b038\u003e","ok_to_retry":false}
```

Here is the stack trace:
```
[cpiCmdRunner] 2017/06/26 16:05:48 DEBUG - Rescued Unknown: undefined method `set_api' for #<Class:0x0055c51465b038>. backtrace: /home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core/client.rb:45:in `define'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:508:in `block in <module:Aws>'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:498:in `call'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:498:in `block in add_service'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:497:in `each'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:497:in `add_service'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core/acm.rb:1:in `<top (required)>'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:457:in `const_get'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:457:in `block in sub_modules'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:456:in `each'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:456:in `inject'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:456:in `sub_modules'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.9.6/lib/aws-sdk-core.rb:444:in `eager_autoload!'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/lib/cloud/aws/cloud.rb:69:in `initialize'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/bin/aws_cpi:24:in `new'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/bin/aws_cpi:24:in `block in <main>'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-2.1.1/lib/bosh/cpi/cli.rb:79:in `call'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-2.1.1/lib/bosh/cpi/cli.rb:79:in `run'
/home/ec2-user/.bosh/installations/1bc6d574-915a-4d31-52ed-f9b34e894c4b/packages/bosh_aws_cpi/bin/aws_cpi:29:in `<main>'
```

**Comment by cdutra** [comment]
@mkjelland Could you provide what version of bosh, aws-cpi and stemcell you're using?
The aws-sdk uses reflection to load services' libs and one of these clients doesn't seem to have the `set_api` method.

**Comment by cdutra** [comment]
Also referenced on [bbl-users](https://cloudfoundry.slack.com/archives/C2DBC3YGZ/p1498154065795336) slack channel.

**Comment by cdutra** [comment]
@mkjelland Could you also provide which AMI's worked and which ones didn't, please? Thanks

**Comment by mkjelland** [comment]
bosh: version 2.0.26 
bosh-aws-xen-hvm-ubuntu-trusty-go_agent stemcell: version 3421.9
aws-cpi: version 65

ami-6df1e514 (Amazon Linux) didn't work, ami-835b4efa and ami-d15a75c7 (Ubuntu Server) both worked.

**Comment by mkjelland** [comment]
I saw this issue when I used `bosh create-env` directly, and when I tried to use bbl (v3.2.5). Thanks!

**Comment by barutm** [comment]
Hi,

Any updates / way around on this issue? I got the same by trying to setup concourse-up (even on the Ubuntu Server AMIs mentioned above). 

Thanks,

**Comment by chenziliang** [comment]
encountered same issue

**Comment by blurblah** [comment]
I had a same issue. bosh create-env did not work on ubuntu 16.04, but worked on 14.04. I don't know why create-env fails on it. If you did on ubuntu 16.04 then use other vm which provisioned ubuntu 14.04. And you will face an invalid argument problem of jq if you use ubuntu 14.04. Because jq v1.3 will be installed through apt-get and v1.3 does not have some options. So you'd rather download and install jq v1.5 than use package manager.

**Comment by astonehal** [comment]
Hi,

I kept on hitting this issue no matter which version of ubuntu I had until I found this page - https://bosh.io/docs/cli-env-deps.html.

After installing all the dependant packages described on the page for Ubuntu Trusty it worked correctly.

Hope this helps as this problem drove me mad for a few days :-)

Thank You

Allan

**Comment by cdutra** [comment]
This seems it can be closed since vm was missing dependencies.
